In [10]:
import pandas as pd

In [96]:
df = pd.read_csv('Econ_Charactristics_Hamilton_Tracts.csv')
df

,Label (Grouping),EMPLOYMENT STATUS,EMPLOYMENT STATUS!!Population 16 years and over,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Civilian labor force,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Civilian labor force!!Employed,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Civilian labor force!!Unemployed,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Armed Forces,EMPLOYMENT STATUS!!Population 16 years and over!!Not in labor force,EMPLOYMENT STATUS!!Civilian labor force,...,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!Under 18 years,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!Under 18 years!!Related children of the householder under 18 years,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!Under 18 years!!Related children of the householder under 18 years!!Related children of the householder under 5 years,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!Under 18 years!!Related children of the householder under 18 years!!Related children of the householder 5 to 17 years,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!18 years and over,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!18 years and over!!18 to 64 years,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!18 years and over!!65 years and over,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!People in families,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!Unrelated individuals 15 years and over
0,"-> Census Tract 4, Hamilton County, Tennessee",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Estimate,NaN,"2,839","1,410","1,410","1,265",145,0,"1,429","1,410",...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
2,Percent,NaN,"2,839",49.7%,49.7%,44.6%,5.1%,0.0%,50.3%,"1,410",...,41.1%,86.5%,86.5%,87.6%,85.8%,30.8%,30.7%,31.0%,46.2%,27.3%
3,"-> Census Tract 6, Hamilton County, Tennessee",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Estimate,NaN,"2,881","2,102","2,102","2,018",84,0,779,"2,102",...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,Estimate,NaN,0,0,0,0,0,0,0,0,...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
257,Percent,NaN,0,-,-,-,-,-,-,0,...,-,-,-,-,-,-,-,-,-,-
258,"-> Census Tract 9802, Hamilton County, Tennessee",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259,Estimate,NaN,0,0,0,0,0,0,0,0,...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
260,Percent,NaN,0,-,-,-,-,-,-,0,...,-,-,-,-,-,-,-,-,-,-

In [97]:
tracts = []
for i in range(len(df)):
    if(df['Label (Grouping)'][i] != "\xa0\xa0\xa0\xa0Estimate" and df['Label (Grouping)'][i] != "\xa0\xa0\xa0\xa0Percent"):
        x = df['Label (Grouping)'][i].split(',')[0]
        x = x.split('-> ')[1]
        tracts.append(x)

tracts

['Census Tract 4',
 'Census Tract 6',
 'Census Tract 7',
 'Census Tract 8',
 'Census Tract 11',
 'Census Tract 12',
 'Census Tract 13',
 'Census Tract 14',
 'Census Tract 16',
 'Census Tract 18',
 'Census Tract 19',
 'Census Tract 20',
 'Census Tract 23',
 'Census Tract 24',
 'Census Tract 25',
 'Census Tract 26',
 'Census Tract 28',
 'Census Tract 29',
 'Census Tract 30',
 'Census Tract 31',
 'Census Tract 32',
 'Census Tract 33',
 'Census Tract 34',
 'Census Tract 101.01',
 'Census Tract 101.03',
 'Census Tract 101.04',
 'Census Tract 102.01',
 'Census Tract 102.02',
 'Census Tract 103.03',
 'Census Tract 103.04',
 'Census Tract 103.05',
 'Census Tract 103.06',
 'Census Tract 103.08',
 'Census Tract 103.09',
 'Census Tract 104.11',
 'Census Tract 104.12',
 'Census Tract 104.13',
 'Census Tract 104.31',
 'Census Tract 104.32',
 'Census Tract 104.33',
 'Census Tract 104.34',
 'Census Tract 104.35',
 'Census Tract 105.01',
 'Census Tract 105.02',
 'Census Tract 106',
 'Census Tract 107',
 'Census Tract 108',
 'Census Tract 109.01',
 'Census Tract 109.02',
 'Census Tract 109.04',
 'Census Tract 109.05',
 'Census Tract 110.01',
 'Census Tract 110.03',
 'Census Tract 110.04',
 'Census Tract 111',
 'Census Tract 112.03',
 'Census Tract 112.04',
 'Census Tract 112.05',
 'Census Tract 112.06',
 'Census Tract 113.11',
 'Census Tract 113.14',
 'Census Tract 113.21',
 'Census Tract 113.23',
 'Census Tract 113.24',
 'Census Tract 113.25',
 'Census Tract 113.26',
 'Census Tract 114.02',
 'Census Tract 114.11',
 'Census Tract 114.13',
 'Census Tract 114.42',
 'Census Tract 114.44',
 'Census Tract 114.45',
 'Census Tract 114.46',
 'Census Tract 114.47',
 'Census Tract 114.48',
 'Census Tract 114.49',
 'Census Tract 116',
 'Census Tract 117',
 'Census Tract 118',
 'Census Tract 119',
 'Census Tract 120',
 'Census Tract 121',
 'Census Tract 122',
 'Census Tract 123',
 'Census Tract 124',
 'Census Tract 9801',
 'Census Tract 9802']

In [98]:
import geopandas as gpd

In [99]:
df2 = gpd.read_file('./Tennessee Census Tracts/tl_2016_47_tract.shp')
tracts2 = df2['NAMELSAD'].tolist()

In [100]:
final = set(tracts2).intersection(tracts)

In [101]:
values = pd.DataFrame()
percent = pd.DataFrame()

In [102]:
c = 0
for i in range(len(df)):
    if(df['Label (Grouping)'][i] != "\xa0\xa0\xa0\xa0Estimate" and df['Label (Grouping)'][i] != "\xa0\xa0\xa0\xa0Percent"):
        x = df['Label (Grouping)'][i].split(',')[0]
        x = x.split('-> ')[1]
        if(x in final):
            values = values.append(df.loc[i+1], ignore_index=True)
            values['Label (Grouping)'][c] = x
            percent = percent.append(df.loc[i+2], ignore_index=True)
            percent['Label (Grouping)'][c] = x
            c+=1

<ipython-input-102-b0ebfad342e3>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  values = values.append(df.loc[i+1], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  values['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  percent = percent.append(df.loc[i+2], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  percent['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  values = values.append(df.loc[i+1], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  values['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  percent = percent.append(df.loc[i+2], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  percent['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  values = values.append(df.loc[i+1], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  values['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  percent = percent.append(df.loc[i+2], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  percent['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  values = values.append(df.loc[i+1], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  values['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  percent = percent.append(df.loc[i+2], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  percent['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  values = values.append(df.loc[i+1], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  values['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  percent = percent.append(df.loc[i+2], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  percent['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  values = values.append(df.loc[i+1], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  values['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  percent = percent.append(df.loc[i+2], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  percent['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  values = values.append(df.loc[i+1], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  values['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  percent = percent.append(df.loc[i+2], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  percent['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  values = values.append(df.loc[i+1], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  values['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  percent = percent.append(df.loc[i+2], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  percent['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  values = values.append(df.loc[i+1], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  values['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  percent = percent.append(df.loc[i+2], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  percent['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  values = values.append(df.loc[i+1], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  values['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  percent = percent.append(df.loc[i+2], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  percent['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  values = values.append(df.loc[i+1], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  values['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  percent = percent.append(df.loc[i+2], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  percent['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  values = values.append(df.loc[i+1], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  values['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  percent = percent.append(df.loc[i+2], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  percent['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  values = values.append(df.loc[i+1], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  values['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  percent = percent.append(df.loc[i+2], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  percent['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  values = values.append(df.loc[i+1], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  values['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  percent = percent.append(df.loc[i+2], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  percent['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  values = values.append(df.loc[i+1], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  values['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  percent = percent.append(df.loc[i+2], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  percent['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  values = values.append(df.loc[i+1], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  values['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  percent = percent.append(df.loc[i+2], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  percent['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  values = values.append(df.loc[i+1], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  values['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  percent = percent.append(df.loc[i+2], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  percent['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  values = values.append(df.loc[i+1], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  values['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  percent = percent.append(df.loc[i+2], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  percent['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  values = values.append(df.loc[i+1], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  values['Label (Grouping)'][c] = x
<ipython-input-102-b0ebfad342e3>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  percent = percent.append(df.loc[i+2], ignore_index=True)
<ipython-input-102-b0ebfad342e3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame


In [103]:
values.rename(columns={'Label (Grouping)': 'NAMELSAD'}, inplace=True)
percent.rename(columns={'Label (Grouping)': 'NAMELSAD'}, inplace=True)

In [104]:
values

,NAMELSAD,EMPLOYMENT STATUS,EMPLOYMENT STATUS!!Population 16 years and over,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Civilian labor force,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Civilian labor force!!Employed,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Civilian labor force!!Unemployed,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Armed Forces,EMPLOYMENT STATUS!!Population 16 years and over!!Not in labor force,EMPLOYMENT STATUS!!Civilian labor force,...,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!Under 18 years,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!Under 18 years!!Related children of the householder under 18 years,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!Under 18 years!!Related children of the householder under 18 years!!Related children of the householder under 5 years,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!Under 18 years!!Related children of the householder under 18 years!!Related children of the householder 5 to 17 years,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!18 years and over,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!18 years and over!!18 to 64 years,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!18 years and over!!65 years and over,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!People in families,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!Unrelated individuals 15 years and over
0,Census Tract 4,NaN,"2,839","1,410","1,410","1,265",145,0,"1,429","1,410",...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
1,Census Tract 6,NaN,"2,881","2,102","2,102","2,018",84,0,779,"2,102",...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
2,Census Tract 7,NaN,"3,875","3,111","3,111","3,043",68,0,764,"3,111",...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
3,Census Tract 8,NaN,"1,692","1,065","1,065","1,026",39,0,627,"1,065",...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
4,Census Tract 11,NaN,"1,424",871,871,843,28,0,553,871,...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,Census Tract 122,NaN,"1,990","1,069","1,069",890,179,0,921,"1,069",...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
74,Census Tract 123,NaN,"3,758","2,392","2,392","2,267",125,0,"1,366","2,392",...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
75,Census Tract 124,NaN,"6,637","3,594","3,594","3,400",194,0,"3,043","3,594",...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
76,Census Tract 9801,NaN,0,0,0,0,0,0,0,0,...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)
77,Census Tract 9802,NaN,0,0,0,0,0,0,0,0,...,(X),(X),(X),(X),(X),(X),(X),(X),(X),(X)

In [105]:
percent

,NAMELSAD,EMPLOYMENT STATUS,EMPLOYMENT STATUS!!Population 16 years and over,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Civilian labor force,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Civilian labor force!!Employed,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Civilian labor force!!Unemployed,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Armed Forces,EMPLOYMENT STATUS!!Population 16 years and over!!Not in labor force,EMPLOYMENT STATUS!!Civilian labor force,...,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!Under 18 years,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!Under 18 years!!Related children of the householder under 18 years,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!Under 18 years!!Related children of the householder under 18 years!!Related children of the householder under 5 years,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!Under 18 years!!Related children of the householder under 18 years!!Related children of the householder 5 to 17 years,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!18 years and over,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!18 years and over!!18 to 64 years,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!18 years and over!!65 years and over,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!People in families,PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All people!!Unrelated individuals 15 years and over
0,Census Tract 4,NaN,"2,839",49.7%,49.7%,44.6%,5.1%,0.0%,50.3%,"1,410",...,41.1%,86.5%,86.5%,87.6%,85.8%,30.8%,30.7%,31.0%,46.2%,27.3%
1,Census Tract 6,NaN,"2,881",73.0%,73.0%,70.0%,2.9%,0.0%,27.0%,"2,102",...,5.9%,1.2%,1.2%,0.0%,1.7%,7.5%,8.5%,2.4%,0.7%,19.4%
2,Census Tract 7,NaN,"3,875",80.3%,80.3%,78.5%,1.8%,0.0%,19.7%,"3,111",...,9.1%,2.6%,2.6%,0.0%,4.5%,10.9%,11.4%,6.6%,1.6%,28.9%
3,Census Tract 8,NaN,"1,692",62.9%,62.9%,60.6%,2.3%,0.0%,37.1%,"1,065",...,15.4%,13.4%,13.4%,9.8%,19.0%,15.7%,18.3%,6.1%,9.7%,20.8%
4,Census Tract 11,NaN,"1,424",61.2%,61.2%,59.2%,2.0%,0.0%,38.8%,871,...,26.4%,38.6%,36.6%,58.9%,17.9%,25.3%,24.3%,30.8%,11.3%,44.0%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,Census Tract 122,NaN,"1,990",53.7%,53.7%,44.7%,9.0%,0.0%,46.3%,"1,069",...,34.1%,42.5%,41.0%,0.0%,53.5%,31.9%,31.9%,32.1%,32.8%,36.2%
74,Census Tract 123,NaN,"3,758",63.7%,63.7%,60.3%,3.3%,0.0%,36.3%,"2,392",...,27.7%,50.6%,50.6%,67.9%,46.3%,20.8%,23.1%,14.3%,28.4%,26.1%
75,Census Tract 124,NaN,"6,637",54.2%,54.2%,51.2%,2.9%,0.0%,45.8%,"3,594",...,33.5%,0.0%,0.0%,0.0%,0.0%,34.4%,36.2%,8.9%,0.0%,43.7%
76,Census Tract 9801,NaN,0,-,-,-,-,-,-,0,...,-,-,-,-,-,-,-,-,-,-
77,Census Tract 9802,NaN,0,-,-,-,-,-,-,0,...,-,-,-,-,-,-,-,-,-,-

In [106]:
res_val = pd.merge(values, df2, on='NAMELSAD')
res_val

,NAMELSAD,EMPLOYMENT STATUS,EMPLOYMENT STATUS!!Population 16 years and over,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Civilian labor force,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Civilian labor force!!Employed,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Civilian labor force!!Unemployed,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Armed Forces,EMPLOYMENT STATUS!!Population 16 years and over!!Not in labor force,EMPLOYMENT STATUS!!Civilian labor force,...,TRACTCE,GEOID,NAME,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,Census Tract 4,NaN,"2,839","1,410","1,410","1,265",145,0,"1,429","1,410",...,000400,47113000400,4,G5020,S,4700103,0,+35.6423907,-088.8113820,"POLYGON ((-88.82931 35.65026, -88.82931 35.650..."
1,Census Tract 4,NaN,"2,839","1,410","1,410","1,265",145,0,"1,429","1,410",...,000400,47065000400,4,G5020,S,3464124,0,+35.0490555,-085.2766692,"POLYGON ((-85.29803 35.05076, -85.29792 35.050..."
2,Census Tract 4,NaN,"2,839","1,410","1,410","1,265",145,0,"1,429","1,410",...,000400,47141000400,4,G5020,S,6158774,0,+36.1763687,-085.4783675,"POLYGON ((-85.50459 36.16861, -85.50457 36.168..."
3,Census Tract 4,NaN,"2,839","1,410","1,410","1,265",145,0,"1,429","1,410",...,000400,47157000400,4,G5020,S,2276725,91258,+35.1768576,-090.0145439,"POLYGON ((-90.02512 35.16874, -90.02509 35.169..."
4,Census Tract 6,NaN,"2,881","2,102","2,102","2,018",84,0,779,"2,102",...,000600,47113000600,6,G5020,S,1407326,0,+35.6316917,-088.8162630,"POLYGON ((-88.82639 35.62900, -88.82638 35.629..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,Census Tract 9802,NaN,0,0,0,0,0,0,0,0,...,980200,47037980200,9802,G5020,S,3750174,0,+36.0995268,-086.7586124,"POLYGON ((-86.77105 36.11113, -86.77099 36.111..."
177,Census Tract 9802,NaN,0,0,0,0,0,0,0,0,...,980200,47157980200,9802,G5020,S,41266553,4249286,+35.1036852,-090.1408192,"POLYGON ((-90.18863 35.07573, -90.18206 35.089..."
178,Census Tract 9802,NaN,0,0,0,0,0,0,0,0,...,980200,47161980200,9802,G5020,S,101258003,304500,+36.5953752,-087.6871708,"POLYGON ((-87.79863 36.63382, -87.79704 36.634..."
179,Census Tract 9802,NaN,0,0,0,0,0,0,0,0,...,980200,47009980200,9802,G5020,S,379539194,208461,+35.5911087,-083.8383909,"POLYGON ((-84.00042 35.55758, -83.99993 35.558..."
180,Census Tract 9802,NaN,0,0,0,0,0,0,0,0,...,980200,47065980200,9802,G5020,S,26731896,0,+35.0892045,-085.1312515,"POLYGON ((-85.16965 35.09932, -85.16963 35.099..."

In [107]:
res_perc = pd.merge(percent, df2, on='NAMELSAD')
res_perc

,NAMELSAD,EMPLOYMENT STATUS,EMPLOYMENT STATUS!!Population 16 years and over,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Civilian labor force,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Civilian labor force!!Employed,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Civilian labor force!!Unemployed,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Armed Forces,EMPLOYMENT STATUS!!Population 16 years and over!!Not in labor force,EMPLOYMENT STATUS!!Civilian labor force,...,TRACTCE,GEOID,NAME,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,Census Tract 4,NaN,"2,839",49.7%,49.7%,44.6%,5.1%,0.0%,50.3%,"1,410",...,000400,47113000400,4,G5020,S,4700103,0,+35.6423907,-088.8113820,"POLYGON ((-88.82931 35.65026, -88.82931 35.650..."
1,Census Tract 4,NaN,"2,839",49.7%,49.7%,44.6%,5.1%,0.0%,50.3%,"1,410",...,000400,47065000400,4,G5020,S,3464124,0,+35.0490555,-085.2766692,"POLYGON ((-85.29803 35.05076, -85.29792 35.050..."
2,Census Tract 4,NaN,"2,839",49.7%,49.7%,44.6%,5.1%,0.0%,50.3%,"1,410",...,000400,47141000400,4,G5020,S,6158774,0,+36.1763687,-085.4783675,"POLYGON ((-85.50459 36.16861, -85.50457 36.168..."
3,Census Tract 4,NaN,"2,839",49.7%,49.7%,44.6%,5.1%,0.0%,50.3%,"1,410",...,000400,47157000400,4,G5020,S,2276725,91258,+35.1768576,-090.0145439,"POLYGON ((-90.02512 35.16874, -90.02509 35.169..."
4,Census Tract 6,NaN,"2,881",73.0%,73.0%,70.0%,2.9%,0.0%,27.0%,"2,102",...,000600,47113000600,6,G5020,S,1407326,0,+35.6316917,-088.8162630,"POLYGON ((-88.82639 35.62900, -88.82638 35.629..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,Census Tract 9802,NaN,0,-,-,-,-,-,-,0,...,980200,47037980200,9802,G5020,S,3750174,0,+36.0995268,-086.7586124,"POLYGON ((-86.77105 36.11113, -86.77099 36.111..."
177,Census Tract 9802,NaN,0,-,-,-,-,-,-,0,...,980200,47157980200,9802,G5020,S,41266553,4249286,+35.1036852,-090.1408192,"POLYGON ((-90.18863 35.07573, -90.18206 35.089..."
178,Census Tract 9802,NaN,0,-,-,-,-,-,-,0,...,980200,47161980200,9802,G5020,S,101258003,304500,+36.5953752,-087.6871708,"POLYGON ((-87.79863 36.63382, -87.79704 36.634..."
179,Census Tract 9802,NaN,0,-,-,-,-,-,-,0,...,980200,47009980200,9802,G5020,S,379539194,208461,+35.5911087,-083.8383909,"POLYGON ((-84.00042 35.55758, -83.99993 35.558..."
180,Census Tract 9802,NaN,0,-,-,-,-,-,-,0,...,980200,47065980200,9802,G5020,S,26731896,0,+35.0892045,-085.1312515,"POLYGON ((-85.16965 35.09932, -85.16963 35.099..."

In [108]:
res_val['TRACTCE'] = res_val['TRACTCE'].astype(int)
res_perc['TRACTCE'] = res_perc['TRACTCE'].astype(int)

In [109]:
df2 = pd.read_csv("tract_transit_score_home.csv")
df2.rename(columns={'TRACTCE_home': 'TRACTCE'},inplace=True)
df2

    TRACTCE  transit_score
0       400       0.248357
1       600       0.413969
2       700       0.467500
3       800       0.384302
4      1100       0.333375
..      ...            ...
70    12100            NaN
71    12200       0.246271
72    12300       0.257694
73    12400       0.257239
74   980200            NaN

[75 rows x 2 columns]

In [110]:
final_val = pd.merge(res_val, df2, on='TRACTCE')
final_val

,NAMELSAD,EMPLOYMENT STATUS,EMPLOYMENT STATUS!!Population 16 years and over,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Civilian labor force,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Civilian labor force!!Employed,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Civilian labor force!!Unemployed,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Armed Forces,EMPLOYMENT STATUS!!Population 16 years and over!!Not in labor force,EMPLOYMENT STATUS!!Civilian labor force,...,GEOID,NAME,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry,transit_score
0,Census Tract 4,NaN,"2,839","1,410","1,410","1,265",145,0,"1,429","1,410",...,47113000400,4,G5020,S,4700103,0,+35.6423907,-088.8113820,"POLYGON ((-88.82931 35.65026, -88.82931 35.650...",0.248357
1,Census Tract 4,NaN,"2,839","1,410","1,410","1,265",145,0,"1,429","1,410",...,47065000400,4,G5020,S,3464124,0,+35.0490555,-085.2766692,"POLYGON ((-85.29803 35.05076, -85.29792 35.050...",0.248357
2,Census Tract 4,NaN,"2,839","1,410","1,410","1,265",145,0,"1,429","1,410",...,47141000400,4,G5020,S,6158774,0,+36.1763687,-085.4783675,"POLYGON ((-85.50459 36.16861, -85.50457 36.168...",0.248357
3,Census Tract 4,NaN,"2,839","1,410","1,410","1,265",145,0,"1,429","1,410",...,47157000400,4,G5020,S,2276725,91258,+35.1768576,-090.0145439,"POLYGON ((-90.02512 35.16874, -90.02509 35.169...",0.248357
4,Census Tract 6,NaN,"2,881","2,102","2,102","2,018",84,0,779,"2,102",...,47113000600,6,G5020,S,1407326,0,+35.6316917,-088.8162630,"POLYGON ((-88.82639 35.62900, -88.82638 35.629...",0.413969
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,Census Tract 9802,NaN,0,0,0,0,0,0,0,0,...,47037980200,9802,G5020,S,3750174,0,+36.0995268,-086.7586124,"POLYGON ((-86.77105 36.11113, -86.77099 36.111...",NaN
160,Census Tract 9802,NaN,0,0,0,0,0,0,0,0,...,47157980200,9802,G5020,S,41266553,4249286,+35.1036852,-090.1408192,"POLYGON ((-90.18863 35.07573, -90.18206 35.089...",NaN
161,Census Tract 9802,NaN,0,0,0,0,0,0,0,0,...,47161980200,9802,G5020,S,101258003,304500,+36.5953752,-087.6871708,"POLYGON ((-87.79863 36.63382, -87.79704 36.634...",NaN
162,Census Tract 9802,NaN,0,0,0,0,0,0,0,0,...,47009980200,9802,G5020,S,379539194,208461,+35.5911087,-083.8383909,"POLYGON ((-84.00042 35.55758, -83.99993 35.558...",NaN
163,Census Tract 9802,NaN,0,0,0,0,0,0,0,0,...,47065980200,9802,G5020,S,26731896,0,+35.0892045,-085.1312515,"POLYGON ((-85.16965 35.09932, -85.16963 35.099...",NaN

In [111]:
final_perc = pd.merge(res_perc, df2, on='TRACTCE')
final_perc

,NAMELSAD,EMPLOYMENT STATUS,EMPLOYMENT STATUS!!Population 16 years and over,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Civilian labor force,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Civilian labor force!!Employed,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Civilian labor force!!Unemployed,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Armed Forces,EMPLOYMENT STATUS!!Population 16 years and over!!Not in labor force,EMPLOYMENT STATUS!!Civilian labor force,...,GEOID,NAME,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry,transit_score
0,Census Tract 4,NaN,"2,839",49.7%,49.7%,44.6%,5.1%,0.0%,50.3%,"1,410",...,47113000400,4,G5020,S,4700103,0,+35.6423907,-088.8113820,"POLYGON ((-88.82931 35.65026, -88.82931 35.650...",0.248357
1,Census Tract 4,NaN,"2,839",49.7%,49.7%,44.6%,5.1%,0.0%,50.3%,"1,410",...,47065000400,4,G5020,S,3464124,0,+35.0490555,-085.2766692,"POLYGON ((-85.29803 35.05076, -85.29792 35.050...",0.248357
2,Census Tract 4,NaN,"2,839",49.7%,49.7%,44.6%,5.1%,0.0%,50.3%,"1,410",...,47141000400,4,G5020,S,6158774,0,+36.1763687,-085.4783675,"POLYGON ((-85.50459 36.16861, -85.50457 36.168...",0.248357
3,Census Tract 4,NaN,"2,839",49.7%,49.7%,44.6%,5.1%,0.0%,50.3%,"1,410",...,47157000400,4,G5020,S,2276725,91258,+35.1768576,-090.0145439,"POLYGON ((-90.02512 35.16874, -90.02509 35.169...",0.248357
4,Census Tract 6,NaN,"2,881",73.0%,73.0%,70.0%,2.9%,0.0%,27.0%,"2,102",...,47113000600,6,G5020,S,1407326,0,+35.6316917,-088.8162630,"POLYGON ((-88.82639 35.62900, -88.82638 35.629...",0.413969
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,Census Tract 9802,NaN,0,-,-,-,-,-,-,0,...,47037980200,9802,G5020,S,3750174,0,+36.0995268,-086.7586124,"POLYGON ((-86.77105 36.11113, -86.77099 36.111...",NaN
160,Census Tract 9802,NaN,0,-,-,-,-,-,-,0,...,47157980200,9802,G5020,S,41266553,4249286,+35.1036852,-090.1408192,"POLYGON ((-90.18863 35.07573, -90.18206 35.089...",NaN
161,Census Tract 9802,NaN,0,-,-,-,-,-,-,0,...,47161980200,9802,G5020,S,101258003,304500,+36.5953752,-087.6871708,"POLYGON ((-87.79863 36.63382, -87.79704 36.634...",NaN
162,Census Tract 9802,NaN,0,-,-,-,-,-,-,0,...,47009980200,9802,G5020,S,379539194,208461,+35.5911087,-083.8383909,"POLYGON ((-84.00042 35.55758, -83.99993 35.558...",NaN
163,Census Tract 9802,NaN,0,-,-,-,-,-,-,0,...,47065980200,9802,G5020,S,26731896,0,+35.0892045,-085.1312515,"POLYGON ((-85.16965 35.09932, -85.16963 35.099...",NaN

In [112]:
final_val['COUNTYFP'] = final_val['COUNTYFP'].astype(int)
final_perc['COUNTYFP'] = final_perc['COUNTYFP'].astype(int)

In [113]:
final_val = final_val.loc[final_val['COUNTYFP']==65]
final_perc = final_perc.loc[final_perc['COUNTYFP'] == 65]

In [114]:
final_val = final_val.reset_index(drop = True)
final_perc = final_val.reset_index(drop = True)

In [115]:
final_val.to_csv("Hamilton_Estimates.csv")
final_perc.to_csv("Hamilton_Percents.csv")

In [116]:
final_perc

,NAMELSAD,EMPLOYMENT STATUS,EMPLOYMENT STATUS!!Population 16 years and over,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Civilian labor force,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Civilian labor force!!Employed,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Civilian labor force!!Unemployed,EMPLOYMENT STATUS!!Population 16 years and over!!In labor force!!Armed Forces,EMPLOYMENT STATUS!!Population 16 years and over!!Not in labor force,EMPLOYMENT STATUS!!Civilian labor force,...,GEOID,NAME,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry,transit_score
0,Census Tract 4,NaN,"2,839","1,410","1,410","1,265",145,0,"1,429","1,410",...,47065000400,4,G5020,S,3464124,0,+35.0490555,-085.2766692,"POLYGON ((-85.29803 35.05076, -85.29792 35.050...",0.248357
1,Census Tract 6,NaN,"2,881","2,102","2,102","2,018",84,0,779,"2,102",...,47065000600,6,G5020,S,2738519,491628,+35.0636340,-085.2992272,"POLYGON ((-85.30922 35.05882, -85.30905 35.059...",0.413969
2,Census Tract 7,NaN,"3,875","3,111","3,111","3,043",68,0,764,"3,111",...,47065000700,7,G5020,S,4507920,452603,+35.0750130,-085.2904829,"POLYGON ((-85.30785 35.07267, -85.30781 35.073...",0.467500
3,Census Tract 8,NaN,"1,692","1,065","1,065","1,026",39,0,627,"1,065",...,47065000800,8,G5020,S,1743162,122570,+35.0680866,-085.3142802,"POLYGON ((-85.31936 35.07141, -85.31929 35.071...",0.384302
4,Census Tract 11,NaN,"1,424",871,871,843,28,0,553,871,...,47065001100,11,G5020,S,1697496,0,+35.0396542,-085.2805689,"POLYGON ((-85.29199 35.03998, -85.29172 35.040...",0.333375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,Census Tract 121,NaN,"5,393","3,412","3,412","3,391",21,0,"1,981","3,412",...,47065012100,121,G5020,S,67040995,3001086,+35.0395489,-085.3801644,"POLYGON ((-85.47551 34.98564, -85.47519 34.985...",NaN
71,Census Tract 122,NaN,"1,990","1,069","1,069",890,179,0,921,"1,069",...,47065012200,122,G5020,S,2830666,0,+35.0588799,-085.2575672,"POLYGON ((-85.27130 35.05626, -85.26976 35.057...",0.246271
72,Census Tract 123,NaN,"3,758","2,392","2,392","2,267",125,0,"1,366","2,392",...,47065012300,123,G5020,S,13142985,828016,+35.0755240,-085.2536040,"POLYGON ((-85.28878 35.05388, -85.28877 35.054...",0.257694
73,Census Tract 124,NaN,"6,637","3,594","3,594","3,400",194,0,"3,043","3,594",...,47065012400,124,G5020,S,2792792,267513,+35.0440253,-085.2978673,"POLYGON ((-85.30756 35.03952, -85.30741 35.039...",0.257239
74,Census Tract 9802,NaN,0,0,0,0,0,0,0,0,...,47065980200,9802,G5020,S,26731896,0,+35.0892045,-085.1312515,"POLYGON ((-85.16965 35.09932, -85.16963 35.099...",NaN