In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
path = './safegraph.parquet/YEAR=2022/region=TN/city=Chattanooga'
safe_data = pd.read_parquet(path, engine='pyarrow')

In [11]:
pd.set_option('display.max_columns', None)
safe_data.head()

,brands,bucketed_dwell_times,category_tags,closed_on,date_begin,date_end,date_range_end,date_range_start,dayofmonth,device_type,distance_from_home,enclosed,geometry_type,includes_parking_lot,is_synthetic,iso_country_code,latitude,location_name,longitude,median_dwell,month,naics_code,normalized_visits_by_region_naics_visitors,normalized_visits_by_region_naics_visits,normalized_visits_by_state_scaling,normalized_visits_by_total_visitors,normalized_visits_by_total_visits,open_hours,opened_on,parent_placekey,phone_number,placekey,poi_cbg,polygon_class,polygon_wkt,postal_code,raw_visit_counts,raw_visitor_counts,related_same_day_brand,related_same_week_brand,safegraph_brand_ids,street_address,sub_category,top_category,tracking_closed_since,visitor_country_of_origin,visitor_daytime_cbgs,visitor_home_aggregation,visitor_home_cbgs,visits_by_day,visits_by_each_hour,visits_friday,visits_monday,visits_saturday,visits_sunday,visits_thursday,visits_tuesday,visits_wednesday,wkt_area_sq_meters
0,nan,"{""<5"":0,""5-10"":7,""11-20"":1,""21-60"":6,""61-120"":...",Gourmet,nan,2022-03-07,2022-03-14,2022-03-14T00:00:00-04:00,2022-03-07T00:00:00-05:00,7,"{""android"":7,""ios"":9}",16276.0,false,POLYGON,false,false,US,35.051542,Nature's Sunshine Distributor,-85.150287,24.0,3,446191.0,0.000148,0.000114,227.831341,0.000005,0.000002,"{ ""Mon"": [[""9:00"", ""18:00""]], ""Tue"": [[""9:00"",...",nan,nan,NaN,zzw-222@8g9-27z-vvf,4.706501e+11,OWNED_POLYGON,POLYGON ((-85.15037442716003 35.05151565896911...,37421.0,22.0,17.0,"{""Walmart"":14,""Target"":5,""Life Care Centers of...","{""Walmart"":59,""Starbucks"":24,""Circle K"":24,""Ch...",nan,7232 Lee Hwy,Food (Health) Supplement Stores,Health and Personal Care Stores,2019-07-01,"{""US"":15}","{""470650112014"":4,""470650111002"":4,""4701101120...","{""13295020901"":5,""47011010100"":4,""47065010432""...","{""130470303041"":4,""470650111002"":4,""1304703020...","[5,7,1,4,1,2,2]","[0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,1,0,0,0,0,1,0,0...",1,5,2,2,4,7,1,120.0
1,nan,"{""<5"":0,""5-10"":4,""11-20"":0,""21-60"":2,""61-120"":...",Gourmet,nan,2022-03-14,2022-03-21,2022-03-21T00:00:00-04:00,2022-03-14T00:00:00-04:00,14,"{""android"":7,""ios"":0}",15451.0,false,POLYGON,false,false,US,35.051542,Nature's Sunshine Distributor,-85.150287,79.0,3,446191.0,0.000100,0.000079,152.146809,0.000003,0.000001,"{ ""Mon"": [[""9:00"", ""18:00""]], ""Tue"": [[""9:00"",...",nan,nan,NaN,zzw-222@8g9-27z-vvf,4.706501e+11,OWNED_POLYGON,POLYGON ((-85.15037442716003 35.05151565896911...,37421.0,15.0,9.0,"{""Walmart"":13,""aerie"":13,""IHOP"":7,""Chili's Gri...","{""The Home Depot"":33,""Circle K"":33,""Taco Bell""...",nan,7232 Lee Hwy,Food (Health) Supplement Stores,Health and Personal Care Stores,2019-07-01,"{""US"":11}",{},{},{},"[2,3,3,2,2,2,1]","[0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0...",2,2,2,1,2,3,3,120.0
2,nan,"{""<5"":0,""5-10"":6,""11-20"":1,""21-60"":6,""61-120"":...",Gourmet,nan,2022-04-25,2022-05-02,2022-05-02T00:00:00-04:00,2022-04-25T00:00:00-04:00,25,"{""android"":7,""ios"":13}",13997.0,false,POLYGON,false,false,US,35.051542,Nature's Sunshine Distributor,-85.150287,62.0,4,446191.0,0.000201,0.000159,259.734961,0.000006,0.000002,"{ ""Mon"": [[""9:00"", ""18:00""]], ""Tue"": [[""9:00"",...",nan,nan,NaN,zzw-222@8g9-27z-vvf,4.706501e+11,OWNED_POLYGON,POLYGON ((-85.15037442716003 35.05151565896911...,37421.0,27.0,21.0,"{""aerie"":12,""Chick-fil-A"":8,""Walmart"":4,""Fairf...","{""Walmart"":48,""Chick-fil-A"":33,""Dollar General...",nan,7232 Lee Hwy,Food (Health) Supplement Stores,Health and Personal Care Stores,2019-07-01,"{""US"":20}","{""130470304023"":4,""470650122001"":4,""4706500310...","{""13047030301"":4}","{""130470303013"":6,""132950203011"":4,""4701101150...","[1,3,4,9,0,5,5]","[0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0...",0,1,5,5,9,3,4,120.0
3,nan,"{""<5"":0,""5-10"":3,""11-20"":2,""21-60"":5,""61-120"":...",Gourmet,nan,2022-03-21,2022-03-28,2022-03-28T00:00:00-04:00,2022-03-21T00:00:00-04:00,21,"{""android"":4,""ios"":8}",13510.0,false,POLYGON,false,false,US,35.051542,Nature's Sunshine Distributor,-85.150287,66.0,3,446191.0,0.000150,0.000117,219.304060,0.000004,0.000002,"{ ""Mon"": [[""9:00"", ""18:00""]], ""Tue"": [[""9:00"",...",nan,nan,NaN,zzw-222@8g9-27z-vvf,4.706501e+11,OWNED_POLYGON,POLYGON ((-85.15037442716003 35.05151565896911...,37421.0,23.0,13.0,"{""aerie"":18,""Taco Bell"":14,""Circle K"":14,""Doll...","{""Taco Bell"":31,""Circle K"":31,""Walmart"":23,""Ma...",nan,7232 Lee Hwy,Food (Health) Supplement Stores,Health and Personal Care Stores,2019-07-01,"{""US"":10}","{""470650104111"":4,""470650114431"":4}","{""47065011311"":4}","{""470650104111"":4}","[2,3,5,2,4,4,3]","[0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0...",4,2,4,3,2,3,5,120.0
4,nan,"{""<5"":0,""5-10"":4,""11-20"":1,""21-60"":1,""61-120"":...",Gourmet,nan,2022-04-04,2022-04-11,2022-04-11T00:00:00-04:00,2022-04-04T00:00:00-04:00,4,"{""android"":5,""ios"":0}",10191.0,false,POLYGON,false,false,US,35.051542,Nature's Sunshine Distributor,-85.150287,101.0,4,446191.0,0.000118,0.000093,175.777916,0.000003,0.000001,"{ ""Mon"": [[""9:00"", ""18:00""]], ""Tue"": [[""9:00"",...",nan,nan,NaN,zzw-222@8g9-27z-vvf,4.706501e+11,OWNED_POLYGON,POLYGON ((-85.15037442716003 35.05151565896911...,37421.0,17.0,11.0,"{""Walmart"":13,""Food Lion"":13,""Sonic"":6,""Raymon...","{""Walmart"":27,""Circle K"":27,""Chick-fil-A"":27,""...",nan,7232 Lee Hwy,Food (Health) Supplement Stores,Health and Personal Care Stores,2019-07-01,"{""US"":10}","{""470650114421"":4,""132950203014"":4}","{""47065011700"":4,""47065010432"":4}","{""470650114453"":4,""130470303041"":4,""4706501220...","[4,2,3,1,2,1,4]","[0,0,0,0,0,2,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0...",2,4,1,4,1,2,3,120.0

In [3]:
safe_clean = safe_data[['date_begin', 'date_end', 'dayofmonth', 'category_tags', 'visits_by_each_hour', 'visits_by_day', 'visitor_country_of_origin', 'visitor_daytime_cbgs', 'visitor_home_aggregation', 'visitor_home_cbgs', 'poi_cbg']]
safe_clean = safe_clean.sort_values(['date_begin'])

In [4]:
ham_blocks =  gpd.read_file('./HamiltonCensusBlocks.geojson')
ham_cbg =  gpd.read_file('./ham_2020_cbg.geojson')

In [5]:
ham_cbg.geoid20 = ham_cbg.geoid20.astype(float)
ham_blocks.geoid20 = ham_blocks.geoid20.astype(float)

In [8]:
ham_cbg2 = gpd.read_file('../Tennessee Census Block Groups/tl_2020_47_bg.shp')

c:\Users\senr1\AppData\Local\Programs\Python\Python37\lib\site-packages\geopandas\array.py:85: ShapelyDeprecationWarning: __len__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Check the length of the `geoms` property instead to get the  number of parts of a multi-part geometry.
  aout[:] = out

In [9]:
ham_cbg2

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,GEOID,NAMELSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,47,165,021106,2,471650211062,Block Group 2,G5030,S,1984864,12123,+36.3020359,-086.6256417,"POLYGON ((-86.63674 36.30110, -86.63593 36.301..."
1,47,185,935100,3,471859351003,Block Group 3,G5030,S,65837822,903019,+36.0162958,-085.5785347,"POLYGON ((-85.64460 36.01505, -85.64392 36.017..."
2,47,185,935300,2,471859353002,Block Group 2,G5030,S,17194664,24762,+35.9142401,-085.4917377,"POLYGON ((-85.52484 35.94395, -85.52480 35.944..."
3,47,185,935100,1,471859351001,Block Group 1,G5030,S,97617866,20569,+36.0275227,-085.4168139,"POLYGON ((-85.50698 36.07420, -85.50650 36.079..."
4,47,185,935000,2,471859350002,Block Group 2,G5030,S,126335613,321921,+35.8565322,-085.3856210,"POLYGON ((-85.49013 35.83724, -85.49012 35.837..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4557,47,119,010301,3,471190103013,Block Group 3,G5030,S,32778660,52176,+35.6594429,-086.8659528,"POLYGON ((-86.91011 35.66576, -86.91011 35.666..."
4558,47,119,011004,2,471190110042,Block Group 2,G5030,S,2636159,0,+35.5319175,-087.2155510,"POLYGON ((-87.22260 35.52095, -87.22259 35.521..."
4559,47,119,011003,1,471190110031,Block Group 1,G5030,S,46364169,286860,+35.4674449,-087.1610359,"POLYGON ((-87.21197 35.52210, -87.21197 35.522..."
4560,47,119,011003,2,471190110032,Block Group 2,G5030,S,59308961,0,+35.4651717,-087.2152726,"POLYGON ((-87.27929 35.44060, -87.27926 35.440..."
4561,47,119,010802,2,471190108022,Block Group 2,G5030,S,4289701,0,+35.6141271,-087.0795043,"POLYGON ((-87.09696 35.62276, -87.09694 35.623..."

In [55]:
safe_clean

,date_begin,date_end,dayofmonth,category_tags,visits_by_each_hour,visits_by_day,visitor_country_of_origin,visitor_daytime_cbgs,visitor_home_aggregation,visitor_home_cbgs,poi_cbg
14,2022-01-03,2022-01-10,3,Gourmet,"[0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0...","[3,3,2,1,2,1,2]","{""US"":8}","{""470650114431"":4}","{""47065010201"":4,""47011011602"":4}","{""470650103051"":4,""130470303041"":4,""4706501020...",4.706501e+11
28,2022-01-03,2022-01-10,3,"Advertising,Marketing","[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...","[0,0,3,2,0,0,0]",nan,{},{},{},4.706501e+11
58,2022-01-03,2022-01-10,3,"Arts and Crafts,Embroidery and Crochet,Screen ...","[0,0,0,0,0,1,0,0,2,1,3,0,0,0,3,0,1,1,0,0,0,0,0...","[12,13,19,13,18,15,6]","{""US"":71}","{""470650114021"":5,""470650114135"":4,""4706501141...","{""47065011413"":10,""47065011411"":8,""47065011445...","{""470650101032"":4,""470650114112"":4,""4701101140...",4.706501e+11
73,2022-01-03,2022-01-10,3,"Jewelry,Piercing","[0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0...","[2,0,0,0,0,1,0]",{},{},"{""47065010306"":4}",{},4.706501e+11
90,2022-01-03,2022-01-10,3,"Counter Service,Salad,Sandwich Shop,Lunch,Brea...","[0,0,0,0,0,0,1,1,0,0,0,8,9,4,4,2,3,1,2,0,0,0,0...","[35,45,45,23,44,39,40]","{""US"":238}","{""470650104321"":12,""470650104311"":9,""470650104...","{""47065010411"":15,""47065010202"":15,""4706501043...","{""470650104111"":10,""470650102023"":9,""470650104...",4.706501e+11
...,...,...,...,...,...,...,...,...,...,...,...
78943,2022-04-25,2022-05-02,25,nan,"[0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...","[1,3,5,5,2,3,5]","{""US"":11}","{""133130003022"":4,""470650114432"":4}","{""13047030202"":4,""47065010307"":4}","{""130470302021"":4,""470650113111"":4,""1331300030...",4.706501e+11
78960,2022-04-25,2022-05-02,25,nan,"[0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0...","[2,1,2,2,3,1,4]","{""US"":12}","{""130470303012"":5,""470650113241"":4,""4706501043...","{""12129010201"":4,""13313000700"":4,""47011011401"":4}","{""470650105013"":4,""130470303012"":4}",4.706501e+11
78977,2022-04-25,2022-05-02,25,"Snacks,Sandwich Shop,Discount Store,Coffee Sho...","[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0...","[3,3,5,1,10,3,5]","{""US"":28}","{""470650113232"":6,""470650113214"":5,""4701101060...","{""47065011323"":8,""47007953100"":4,""47011010600""...","{""470650113142"":4,""132950206011"":4,""4700795310...",4.706501e+11
78994,2022-04-25,2022-05-02,25,"Oil Changes,Propane","[0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,2,0,2,1,0,1,0,0...","[7,6,2,6,5,7,6]","{""US"":32}","{""470659802001"":7,""470650113214"":4,""4705396650...","{""47065002500"":7,""13047030202"":4,""47065001900""...","{""470650106002"":4,""470650113214"":4,""4706501230...",4.706500e+11
79012,2022-04-25,2022-05-02,25,nan,"[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0...","[2,1,0,0,1,1,2]","{""US"":7}","{""470650011001"":4}","{""47065011326"":6}","{""470650004001"":4}",4.706500e+11

In [66]:
s2 = safe_clean.merge(ham_cbg, left_on='poi_cbg', right_on='geoid20')
s2[s2.tractce20=='980200']

,date_begin,date_end,dayofmonth,category_tags,visits_by_each_hour,visits_by_day,visitor_country_of_origin,visitor_daytime_cbgs,visitor_home_aggregation,visitor_home_cbgs,poi_cbg,countyfp20,tractce20,blkgrpce20,geoid20,statefp20,geometry
65688,2022-01-03,2022-01-10,3,Car Dealers,"[0,0,0,0,0,4,2,0,1,1,1,1,1,2,2,1,1,0,0,2,0,0,0...","[19,23,30,37,19,4,2]","{""US"":62}","{""470659802001"":13,""470650104311"":6,""470650112...","{""47065011402"":7,""47065011411"":5,""47065010304""...","{""210099510001"":4,""471759250001"":4,""4706501131...",4.706598e+11,065,980200,1,4.706598e+11,47,"POLYGON ((-85.16138 35.07340, -85.16136 35.073..."
65689,2022-01-03,2022-01-10,3,nan,"[0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0...","[2,5,7,7,11,1,0]","{""US"":10}","{""470659802001"":4,""470110114012"":4}","{""47065010101"":4,""37001021204"":4,""12089050302""...","{""370010212042"":4,""470650118006"":4,""4706501141...",4.706598e+11,065,980200,1,4.706598e+11,47,"POLYGON ((-85.16138 35.07340, -85.16136 35.073..."
65690,2022-01-03,2022-01-10,3,nan,"[0,0,0,0,0,0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0...","[5,5,17,1,10,3,0]","{""US"":14}","{""470650114133"":6,""470650113242"":4,""1329502040...","{""47065011402"":4,""47065012300"":4,""13295020400""...","{""132950204003"":4,""130830402002"":4}",4.706598e+11,065,980200,1,4.706598e+11,47,"POLYGON ((-85.16138 35.07340, -85.16136 35.073..."
65691,2022-01-03,2022-01-10,3,Corporate Offices,"[2,3,2,4,3,6,22,22,7,10,7,6,7,3,4,5,4,8,7,11,4...","[159,163,182,196,127,116,119]","{""US"":253}","{""470659802001"":13,""511076110132"":7,""471150502...","{""47065011413"":7,""47065011326"":5,""47065002800""...","{""470650029001"":5,""470659802001"":5,""4713995020...",4.706598e+11,065,980200,1,4.706598e+11,47,"POLYGON ((-85.16138 35.07340, -85.16136 35.073..."
65692,2022-01-03,2022-01-10,3,nan,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0...","[1,4,5,0,2,10,0]","{""US"":18}","{""470650114135"":4,""470650114132"":4,""4706501010...","{""01073012803"":4,""47065011201"":4,""47065011413""...","{""470650114132"":5,""470650114134"":4,""4706501120...",4.706598e+11,065,980200,1,4.706598e+11,47,"POLYGON ((-85.16138 35.07340, -85.16136 35.073..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65887,2022-04-25,2022-05-02,25,Corporate Offices,"[1,1,2,5,4,0,19,17,3,2,5,2,7,1,4,8,4,8,20,4,29...","[156,162,165,138,117,93,125]","{""US"":248}","{""360470288002"":6,""120860115005"":6,""4706501140...","{""47011011602"":9,""47065010201"":8,""47065011326""...","{""130470306002"":8,""132950203025"":6,""1304703050...",4.706598e+11,065,980200,1,4.706598e+11,47,"POLYGON ((-85.16138 35.07340, -85.16136 35.073..."
65888,2022-04-25,2022-05-02,25,nan,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...","[0,0,1,0,0,46,72]","{""US"":75}","{""470650112033"":6,""470650107001"":6,""4706501050...","{""47065011447"":5,""47065011600"":4,""47065011445""...","{""470650116001"":5,""130470307001"":4,""1209501670...",4.706598e+11,065,980200,1,4.706598e+11,47,"POLYGON ((-85.16138 35.07340, -85.16136 35.073..."
65889,2022-04-25,2022-05-02,25,"Diagnostic Services,Laboratory Testing","[0,0,0,0,0,1,0,4,2,2,3,1,2,0,0,0,2,0,0,0,0,0,0...","[17,25,15,20,16,0,0]","{""US"":55}","{""470659802001"":8,""470650114461"":4,""4706501131...","{""47065010413"":5,""13055010200"":4,""47093005706""...","{""470650114024"":6,""130470304023"":4,""4706501120...",4.706598e+11,065,980200,1,4.706598e+11,47,"POLYGON ((-85.16138 35.07340, -85.16136 35.073..."
65890,2022-04-25,2022-05-02,25,nan,"[0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0...","[2,7,3,3,5,0,0]","{""US"":9}","{""470659802001"":6}","{""47065010431"":4,""47065011447"":4}","{""470650112011"":4,""470650104313"":4}",4.706598e+11,065,980200,1,4.706598e+11,47,"POLYGON ((-85.16138 35.07340, -85.16136 35.073..."
65891,2022-04-25,2022-05-02,25,Cafe,"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0...","[1,3,0,2,0,0,0]","{""US"":7}","{""470650112031"":4}","{""47065011326"":4}","{""470650113263"":4}",4.706598e+11,065,980200,1,4.706598e+11,47,"POLYGON ((-85.16138 35.07340, -85.16136 35.073..."